/* ==========================================================================
   Bangladesh Bank AD (ICT) — Written Prep
   js/search-index.js

   A plain global array, not a module, so it loads from file:// without CORS.

   Schema, kept short because every byte is repeated ~200 times:
     p   page path, relative to the site root
     s   subject name, shown as the result subtitle
     t   title, what the user reads and what is matched first
     h   element id to jump to (optional)
     ty  "subject" | "notes" | "solved" | "practice"
     k   extra keywords that should match but are not in the title

   app.js resolves p against the <html data-root> attribute, so the same
   entries work from the hub page and from inside subjects/.

   All 18 subjects plus the past-papers page are indexed below.
   ========================================================================== */

window.SEARCH_INDEX = [
  /* ---------------------------------------------------------------- pages */
  { p: "index.html", s: "Site", t: "Home — all subjects", ty: "subject", k: "index hub start coverage map progress" },
  { p: "subjects/computer-fundamentals.html", s: "Subject 01", t: "Computer Fundamentals", ty: "subject", k: "generation number system binary memory storage malware encoding port bus" },
  { p: "subjects/c-programming.html", s: "Subject 02", t: "C Programming", ty: "subject", k: "pointer array string struct function recursion output prediction memory" },
  { p: "subjects/data-structures.html", s: "Subject 03", t: "Data Structures", ty: "subject", k: "array linked list stack queue tree heap graph sorting hashing" },
  { p: "subjects/algorithms.html", s: "Subject 04", t: "Algorithms", ty: "subject", k: "complexity master theorem greedy dynamic programming np" },
  { p: "subjects/database.html", s: "Subject 05", t: "Database", ty: "subject", k: "sql normalization er model transaction raid nosql acid indexing" },
  { p: "subjects/oop-java.html", s: "Subject 06", t: "OOP (Java)", ty: "subject", k: "inheritance polymorphism abstraction encapsulation interface exception string collections" },
  { p: "subjects/networking.html", s: "Subject 07", t: "Data Communication and Networking", ty: "subject", k: "osi tcp ip subnetting crc ethernet dns http" },
  { p: "subjects/computer-architecture.html", s: "Subject 08", t: "Computer Architecture", ty: "subject", k: "pipeline cache ieee 754 amdahl booth addressing mode risc cisc 8085 8086" },
  { p: "subjects/operating-system.html", s: "Subject 11", t: "Operating System", ty: "subject", k: "process thread scheduling deadlock memory paging disk linux" },

  /* ------------------------------------------------- data structures notes */
  { p: "subjects/data-structures.html", h: "n-foundations", s: "Data Structures", t: "Foundations — ADT, linear vs non-linear, complexity", ty: "notes", k: "abstract data type static dynamic best average worst case operation cost grid" },
  { p: "subjects/data-structures.html", h: "n-arrays", s: "Data Structures", t: "Arrays and address calculation", ty: "notes", k: "row major column major base address sparse matrix triplet insertion deletion cost" },
  { p: "subjects/data-structures.html", h: "n-linked-lists", s: "Data Structures", t: "Linked lists — singly, doubly, circular", ty: "notes", k: "reverse middle floyd cycle detection merge header node array vs linked list" },
  { p: "subjects/data-structures.html", h: "n-stack", s: "Data Structures", t: "Stack — infix, postfix, prefix, Tower of Hanoi", ty: "notes", k: "lifo push pop overflow underflow precedence associativity parenthesis matching" },
  { p: "subjects/data-structures.html", h: "n-queue", s: "Data Structures", t: "Queue — circular, deque, priority queue", ty: "notes", k: "fifo enqueue dequeue front rear queue using two stacks stack using two queues" },
  { p: "subjects/data-structures.html", h: "n-trees", s: "Data Structures", t: "Trees — terminology, formulas, traversals", ty: "notes", k: "root leaf height depth level full complete perfect skewed preorder inorder postorder level order threaded expression tree reconstruction" },
  { p: "subjects/data-structures.html", h: "n-bst", s: "Data Structures", t: "Binary search tree — insert, search, delete", ty: "notes", k: "inorder successor predecessor kth smallest three deletion cases degradation" },
  { p: "subjects/data-structures.html", h: "n-balanced", s: "Data Structures", t: "AVL, red-black, B-tree and B+ tree", ty: "notes", k: "balance factor rotation ll rr lr rl why databases use b plus tree 2-3 tree" },
  { p: "subjects/data-structures.html", h: "n-heap", s: "Data Structures", t: "Heaps and priority queues", ty: "notes", k: "min heap max heap heapify build heap index formula parent child heap sort why build is o(n)" },
  { p: "subjects/data-structures.html", h: "n-hashing", s: "Data Structures", t: "Hashing — collisions, probing, load factor", ty: "notes", k: "chaining linear quadratic double hashing primary secondary clustering rehashing division method" },
  { p: "subjects/data-structures.html", h: "n-graphs", s: "Data Structures", t: "Graphs — representation, BFS, DFS, MST, shortest path", ty: "notes", k: "adjacency matrix list incidence topological sort bipartite cycle detection kruskal prim dijkstra bellman ford floyd warshall scc" },
  { p: "subjects/data-structures.html", h: "n-trie", s: "Data Structures", t: "Tries and disjoint sets", ty: "notes", k: "prefix tree autocomplete union find union by rank path compression inverse ackermann" },
  { p: "subjects/data-structures.html", h: "n-searching", s: "Data Structures", t: "Searching — linear, binary, jump, interpolation", ty: "notes", k: "rotated sorted array ternary search complexity comparison" },
  { p: "subjects/data-structures.html", h: "n-sorting", s: "Data Structures", t: "Sorting — full comparison table", ty: "notes", k: "bubble selection insertion merge quick heap counting radix bucket shell stable in-place adaptive which to choose" },
  { p: "subjects/data-structures.html", h: "n-lower-bound", s: "Data Structures", t: "The Ω(n log n) comparison-sort lower bound", ty: "notes", k: "decision tree stirling why radix beats it" },

  /* ---------------------------------------------- data structures questions */
  { p: "subjects/data-structures.html", h: "s1", s: "Data Structures", t: "Convert an array into a min-heap, step by step", ty: "solved", k: "build heap heapify past paper 2025 bottom up" },
  { p: "subjects/data-structures.html", h: "s2", s: "Data Structures", t: "Address of A[i][j] in row-major and column-major order", ty: "solved", k: "base address element size array bounds total size" },
  { p: "subjects/data-structures.html", h: "s3", s: "Data Structures", t: "Infix to postfix with a stack trace, then evaluate", ty: "solved", k: "expression conversion precedence operand order" },
  { p: "subjects/data-structures.html", h: "s4", s: "Data Structures", t: "Build a BST, give all traversals, delete three nodes", ty: "solved", k: "insertion deletion two children inorder successor" },
  { p: "subjects/data-structures.html", h: "s5", s: "Data Structures", t: "Reconstruct a tree from inorder and preorder", ty: "solved", k: "postorder height leaves why preorder plus postorder is not unique" },
  { p: "subjects/data-structures.html", h: "s6", s: "Data Structures", t: "AVL insertion with LL, RR, LR and RL rotations", ty: "solved", k: "balance factor double rotation rebalancing trace" },
  { p: "subjects/data-structures.html", h: "s7", s: "Data Structures", t: "Hash table with linear probing versus chaining", ty: "solved", k: "load factor average probes primary clustering comparison" },
  { p: "subjects/data-structures.html", h: "s8", s: "Data Structures", t: "BFS and DFS order, bipartite check, matrix vs list memory", ty: "solved", k: "graph traversal two colouring adjacency space" },
  { p: "subjects/data-structures.html", h: "s9", s: "Data Structures", t: "Minimum spanning tree by Kruskal and by Prim", ty: "solved", k: "cut property total weight cycle rejection" },
  { p: "subjects/data-structures.html", h: "s10", s: "Data Structures", t: "Dijkstra shortest path with a full distance table", ty: "solved", k: "relaxation predecessor negative edges why it fails" },
  { p: "subjects/data-structures.html", h: "p1", s: "Data Structures", t: "Circular queue trace with overflow and underflow", ty: "practice", k: "front rear modulo full empty condition element count" },
  { p: "subjects/data-structures.html", h: "p2", s: "Data Structures", t: "Reverse a linked list in C, and Floyd's cycle proof", ty: "practice", k: "three pointer iterative tortoise hare o(n) proof" },
  { p: "subjects/data-structures.html", h: "p3", s: "Data Structures", t: "Infix to prefix conversion", ty: "practice", k: "reverse swap brackets right associative expression tree check" },
  { p: "subjects/data-structures.html", h: "p4", s: "Data Structures", t: "Tree formula problems — leaves, height, null pointers", ty: "practice", k: "complete binary tree n0 = n2 + 1 m-ary maximum minimum nodes" },
  { p: "subjects/data-structures.html", h: "p5", s: "Data Structures", t: "Extract-min twice, then heap sort a small array", ty: "practice", k: "sift down max heap ascending why max heap for ascending" },
  { p: "subjects/data-structures.html", h: "p6", s: "Data Structures", t: "Quadratic probing and double hashing compared", ty: "practice", k: "secondary clustering h2 never zero prime table size" },
  { p: "subjects/data-structures.html", h: "p7", s: "Data Structures", t: "Radix sort with bucket contents per pass", ty: "practice", k: "lsd stable counting why it beats the n log n bound" },
  { p: "subjects/data-structures.html", h: "p8", s: "Data Structures", t: "Binary search trace and comparison count", ty: "practice", k: "low high mid unsuccessful search when sorting first pays off" },
  { p: "subjects/data-structures.html", h: "p9", s: "Data Structures", t: "Topological sort by Kahn's algorithm, and cycle detection", ty: "practice", k: "in-degree dag uniqueness prerequisite" },
  { p: "subjects/data-structures.html", h: "p10", s: "Data Structures", t: "Stack from two queues, sparse matrix, array vs list", ty: "practice", k: "triplet representation memory saving break-even" },

  /* ---------------------------------------------------------- algorithms */
  { p: "subjects/algorithms.html", h: "n-analysis", s: "Algorithms", t: "Asymptotic notation and growth-rate ordering", ty: "notes", k: "big o omega theta little o amortised aggregate accounting potential loop analysis" },
  { p: "subjects/algorithms.html", h: "n-recurrence", s: "Algorithms", t: "Recurrences and the Master theorem", ty: "notes", k: "three cases recursion tree substitution when it does not apply gap case" },
  { p: "subjects/algorithms.html", h: "n-divide", s: "Algorithms", t: "Divide and conquer", ty: "notes", k: "merge sort quick sort strassen closest pair maximum subarray karatsuba versus dynamic programming" },
  { p: "subjects/algorithms.html", h: "n-greedy", s: "Algorithms", t: "Greedy algorithms and where they fail", ty: "notes", k: "greedy choice property optimal substructure activity selection huffman job sequencing coin change" },
  { p: "subjects/algorithms.html", h: "n-dp", s: "Algorithms", t: "Dynamic programming — every standard recurrence", ty: "notes", k: "memoisation tabulation knapsack lcs edit distance matrix chain lis rod cutting subset sum pseudo-polynomial" },
  { p: "subjects/algorithms.html", h: "n-backtracking", s: "Algorithms", t: "Backtracking and branch and bound", ty: "notes", k: "n-queens sudoku rat in a maze graph colouring hamiltonian pruning state space" },
  { p: "subjects/algorithms.html", h: "n-graph-algo", s: "Algorithms", t: "Graph algorithms — shortest path comparison, max flow", ty: "notes", k: "dijkstra bellman ford floyd warshall cut property ford fulkerson max flow min cut" },
  { p: "subjects/algorithms.html", h: "n-string", s: "Algorithms", t: "String matching — KMP, Rabin-Karp, Boyer-Moore", ty: "notes", k: "lps failure function rolling hash bad character good suffix" },
  { p: "subjects/algorithms.html", h: "n-number", s: "Algorithms", t: "Number-theoretic algorithms", ty: "notes", k: "euclid extended gcd lcm modular exponentiation sieve primality rsa inverse" },
  { p: "subjects/algorithms.html", h: "n-complexity", s: "Algorithms", t: "Complexity classes — P, NP, NP-hard, NP-complete", ty: "notes", k: "reduction sat tsp clique vertex cover halting problem approximation randomised" },
  { p: "subjects/algorithms.html", h: "s1", s: "Algorithms", t: "Master theorem applied to six recurrences", ty: "solved", k: "case 1 2 3 regularity condition strassen not applicable" },
  { p: "subjects/algorithms.html", h: "s2", s: "Algorithms", t: "Order functions by growth, analyse four loops, prove Θ", ty: "solved", k: "log factorial growth ordering nested loop square root formal proof" },
  { p: "subjects/algorithms.html", h: "s3", s: "Algorithms", t: "0/1 knapsack — full DP table and traceback", ty: "solved", k: "capacity weight value skip or take pseudo polynomial" },
  { p: "subjects/algorithms.html", h: "s4", s: "Algorithms", t: "Huffman coding — tree, code table, average length", ty: "solved", k: "prefix free compression ratio fixed length comparison 224 bits" },
  { p: "subjects/algorithms.html", h: "s5", s: "Algorithms", t: "Longest common subsequence with traceback", ty: "solved", k: "agGTAB gxtxayb subsequence versus substring" },
  { p: "subjects/algorithms.html", h: "s6", s: "Algorithms", t: "Fractional knapsack, and why greedy fails for 0/1", ty: "solved", k: "ratio exchange argument upper bound relaxation" },
  { p: "subjects/algorithms.html", h: "s7", s: "Algorithms", t: "Activity selection and job sequencing with deadlines", ty: "solved", k: "earliest finish time latest free slot profit maximisation" },
  { p: "subjects/algorithms.html", h: "s8", s: "Algorithms", t: "Matrix chain multiplication — m table and parenthesisation", ty: "solved", k: "scalar multiplications split point catalan number" },
  { p: "subjects/algorithms.html", h: "s9", s: "Algorithms", t: "KMP — LPS array construction and matching trace", ty: "solved", k: "failure function why o(n) naive worst case" },
  { p: "subjects/algorithms.html", h: "s10", s: "Algorithms", t: "Bellman-Ford with negative edges and cycle detection", ty: "solved", k: "relaxation passes why dijkstra fails v-1 rounds" },
  { p: "subjects/algorithms.html", h: "p1", s: "Algorithms", t: "Recurrences by recursion tree and back-substitution", ty: "practice", k: "unequal split geometric series depth level cost" },
  { p: "subjects/algorithms.html", h: "p2", s: "Algorithms", t: "Edit distance between SUNDAY and SATURDAY", ty: "practice", k: "levenshtein insert delete substitute traceback kyc name matching" },
  { p: "subjects/algorithms.html", h: "p3", s: "Algorithms", t: "Longest increasing subsequence, both methods", ty: "practice", k: "o(n^2) dp patience sorting tails array why tails is not the answer" },
  { p: "subjects/algorithms.html", h: "p4", s: "Algorithms", t: "Coin change — greedy failure, min coins, counting ways", ty: "practice", k: "canonical coin system denominations combinations" },
  { p: "subjects/algorithms.html", h: "p5", s: "Algorithms", t: "4-queens by backtracking with dead ends shown", ty: "practice", k: "state space pruning both solutions brute force comparison" },
  { p: "subjects/algorithms.html", h: "p6", s: "Algorithms", t: "GCD, extended Euclid, modular exponentiation", ty: "practice", k: "bezout lcm repeated squaring fermat little theorem rsa private exponent" },
  { p: "subjects/algorithms.html", h: "p7", s: "Algorithms", t: "Sieve of Eratosthenes and trial-division primality", ty: "practice", k: "why start at p squared square root bound miller rabin" },
  { p: "subjects/algorithms.html", h: "p8", s: "Algorithms", t: "Rod cutting — maximum revenue and where to cut", ty: "practice", k: "dp table first cut greedy comparison" },
  { p: "subjects/algorithms.html", h: "p9", s: "Algorithms", t: "P, NP, NP-hard, NP-complete and reductions", ty: "practice", k: "two steps to prove np-complete halting problem quantum shor rsa banking" },
  { p: "subjects/algorithms.html", h: "p10", s: "Algorithms", t: "Amortised analysis of a doubling array, and subset sum", ty: "practice", k: "aggregate accounting potential method versus average case" },

  /* ---------------------------------------------------------- networking */
  { p: "subjects/networking.html", h: "n-fundamentals", s: "Networking", t: "Fundamentals — topologies, data flow, network types", ty: "notes", k: "simplex half duplex full duplex mesh star bus ring link formula lan man wan internet intranet extranet isp tier" },
  { p: "subjects/networking.html", h: "n-models", s: "Networking", t: "OSI and TCP/IP reference models", ty: "notes", k: "seven layers pdu devices encapsulation decapsulation comparison mnemonic" },
  { p: "subjects/networking.html", h: "n-physical", s: "Networking", t: "Physical layer — bit rate, baud rate, Nyquist, Shannon", ty: "notes", k: "channel capacity decibel snr attenuation distortion noise utp coaxial fibre satellite" },
  { p: "subjects/networking.html", h: "n-delay", s: "Networking", t: "Delay and latency — the four delays", ty: "notes", k: "transmission propagation queuing processing rtt bandwidth delay product store and forward throughput" },
  { p: "subjects/networking.html", h: "n-digital", s: "Networking", t: "Digital transmission — line coding and PCM", ty: "notes", k: "nrz manchester differential ami b8zs hdb3 sampling quantization delta modulation synchronous asynchronous" },
  { p: "subjects/networking.html", h: "n-analog", s: "Networking", t: "Modulation and multiplexing", ty: "notes", k: "ask fsk psk qpsk qam fdm wdm tdm fhss dsss cdma tdma fdma" },
  { p: "subjects/networking.html", h: "n-switching", s: "Networking", t: "Switching — circuit, packet, virtual circuit, message", ty: "notes", k: "datagram setup phase order preserved comparison table" },
  { p: "subjects/networking.html", h: "n-datalink", s: "Networking", t: "Data link layer — framing, CRC, Hamming, sliding window", ty: "notes", k: "bit stuffing parity checksum error detection stop and wait go-back-n selective repeat piggybacking hdlc ppp efficiency" },
  { p: "subjects/networking.html", h: "n-mac", s: "Networking", t: "Medium access — ALOHA, CSMA/CD, CSMA/CA, devices", ty: "notes", k: "slotted aloha efficiency minimum frame size backoff ethernet mac address arp hub switch bridge router collision broadcast domain vlan spanning tree" },
  { p: "subjects/networking.html", h: "n-network-layer", s: "Networking", t: "Network layer — IPv4, subnetting, IPv6, routing", ty: "notes", k: "header ttl address classes cidr vlsm supernetting nat pat icmp igmp dhcp rip ospf bgp count to infinity unicast multicast anycast" },
  { p: "subjects/networking.html", h: "n-transport", s: "Networking", t: "Transport layer — TCP, UDP, handshake, congestion control", ty: "notes", k: "port socket header three way four way termination slow start aimd fast retransmit recovery tahoe reno cubic" },
  { p: "subjects/networking.html", h: "n-application", s: "Networking", t: "Application layer — DNS, HTTP, HTTPS, FTP, SMTP", ty: "notes", k: "record types mx status codes tls handshake persistent connection ssh telnet snmp ntp ldap proxy cdn cookies" },
  { p: "subjects/networking.html", h: "n-security", s: "Networking", t: "Firewalls, DMZ, IDS, IPS and VPN", ty: "notes", k: "packet filtering stateful application proxy next generation ipsec transport tunnel mode site to site" },
  { p: "subjects/networking.html", h: "n-wireless", s: "Networking", t: "Wireless and modern networking", ty: "notes", k: "802.11 wifi 6 bluetooth wimax 1g 2g 3g 4g 5g manet sdn nfv mpls" },
  { p: "subjects/networking.html", h: "s1", s: "Networking", t: "Dhaka to Rangpur latency and round-trip time", ty: "solved", k: "transmission propagation delay store and forward bandwidth delay product stop and wait efficiency past paper 2025" },
  { p: "subjects/networking.html", h: "s2", s: "Networking", t: "How email travels — SMTP, POP3 and IMAP", ty: "solved", k: "mua mta mda mx lookup push pull comparison spf dkim dmarc past paper 2025" },
  { p: "subjects/networking.html", h: "s3", s: "Networking", t: "Flow control versus congestion control", ty: "solved", k: "rwnd cwnd advertised window aimd silly window nagle past paper 2024" },
  { p: "subjects/networking.html", h: "s4", s: "Networking", t: "Subnetting drills — /27 design and /20 analysis", ty: "solved", k: "subnet mask block size network broadcast valid host range usable hosts" },
  { p: "subjects/networking.html", h: "s5", s: "Networking", t: "CRC computation and receiver verification", ty: "solved", k: "generator polynomial modulo 2 xor division remainder burst error parity comparison" },
  { p: "subjects/networking.html", h: "s6", s: "Networking", t: "Hamming code — encode, then locate and correct an error", ty: "solved", k: "parity bit positions syndrome secded why only single error" },
  { p: "subjects/networking.html", h: "s7", s: "Networking", t: "OSI layers, TCP/IP mapping and encapsulation", ty: "solved", k: "pdu devices mac changes ip stays peer to peer" },
  { p: "subjects/networking.html", h: "s8", s: "Networking", t: "TCP handshake and a congestion window trace", ty: "solved", k: "syn ack fin time_wait slow start ssthresh timeout duplicate acks fast recovery" },
  { p: "subjects/networking.html", h: "s9", s: "Networking", t: "CSMA/CD minimum frame size and network diameter", ty: "solved", k: "slot time 64 bytes 512 bits carrier extension collision broadcast domains hub switch router" },
  { p: "subjects/networking.html", h: "s10", s: "Networking", t: "Topology link counts, baud rate, Nyquist and Shannon", ty: "solved", k: "mesh formula qam bits per symbol channel capacity snr decibel signal levels" },
  { p: "subjects/networking.html", h: "p1", s: "Networking", t: "VLSM design for six segments of different sizes", ty: "practice", k: "variable length subnet mask largest first alignment fixed length impossible" },
  { p: "subjects/networking.html", h: "p2", s: "Networking", t: "Internet checksum, and why TCP checksums over Ethernet", ty: "practice", k: "one's complement end around carry end to end argument router memory corruption" },
  { p: "subjects/networking.html", h: "p3", s: "Networking", t: "Sliding window efficiency and sequence-number bits", ty: "practice", k: "stop and wait throughput optimal window go-back-n selective repeat limits" },
  { p: "subjects/networking.html", h: "p4", s: "Networking", t: "IP fragmentation — offsets, MF flag, overhead", ty: "practice", k: "mtu 1500 multiple of 8 path mtu discovery ipv6 packet too big" },
  { p: "subjects/networking.html", h: "p5", s: "Networking", t: "DNS resolution traced end to end", ty: "practice", k: "recursive iterative root tld authoritative caching ttl udp tcp 512 bytes zone transfer" },
  { p: "subjects/networking.html", h: "p6", s: "Networking", t: "HTTP round trips, the TLS handshake, status codes", ty: "practice", k: "persistent pipelining certificate authority forward secrecy 301 304 401 403 503" },
  { p: "subjects/networking.html", h: "p7", s: "Networking", t: "PCM bit rates and Manchester signal rate", ty: "practice", k: "nyquist sampling 64 kbps cd audio storage clock recovery bandwidth cost" },
  { p: "subjects/networking.html", h: "p8", s: "Networking", t: "RIP, count to infinity, and choosing OSPF or BGP", ty: "practice", k: "distance vector split horizon poison reverse hold down triggered update link state path vector" },
  { p: "subjects/networking.html", h: "p9", s: "Networking", t: "PAT for 200 hosts, and is NAT security?", ty: "practice", k: "translation table port overload firewall types dmz stateful application proxy" },
  { p: "subjects/networking.html", h: "p10", s: "Networking", t: "T1 frame math, statistical TDM, switching choice", ty: "practice", k: "1.544 mbps framing bit efficiency address field atm network mpls" },

  /* ------------------------------------------------- computer fundamentals */
  { p: "subjects/computer-fundamentals.html", h: "n-generations", s: "Computer Fundamentals", t: "Computer generations", ty: "notes", k: "vacuum tube transistor ic vlsi ulsi first second third fourth fifth switching technology" },
  { p: "subjects/computer-fundamentals.html", h: "n-classification", s: "Computer Fundamentals", t: "Classification of computers", ty: "notes", k: "analog digital hybrid micro mini mainframe supercomputer purpose special general" },
  { p: "subjects/computer-fundamentals.html", h: "n-number-systems", s: "Computer Fundamentals", t: "Number systems and arithmetic", ty: "notes", k: "binary octal decimal hexadecimal conversion twos complement ones complement signed magnitude bcd excess-3 gray code" },
  { p: "subjects/computer-fundamentals.html", h: "n-encoding", s: "Computer Fundamentals", t: "Character encoding — ASCII, Unicode, UTF-8", ty: "notes", k: "ascii extended ebcdic unicode utf-8 utf-16 code point variable length" },
  { p: "subjects/computer-fundamentals.html", h: "n-memory", s: "Computer Fundamentals", t: "Memory hierarchy — registers to tape", ty: "notes", k: "sram dram rom prom eprom eeprom flash cache primary secondary volatile non-volatile hierarchy speed cost" },
  { p: "subjects/computer-fundamentals.html", h: "n-storage", s: "Computer Fundamentals", t: "Storage devices and units", ty: "notes", k: "hdd ssd cd dvd blu-ray usb sd card kb mb gb tb pb bit byte nibble sector track cylinder" },
  { p: "subjects/computer-fundamentals.html", h: "n-io", s: "Computer Fundamentals", t: "Input and output devices", ty: "notes", k: "keyboard mouse scanner barcode ocr omr trackball joystick touchscreen monitor printer plotter speaker" },
  { p: "subjects/computer-fundamentals.html", h: "n-ports", s: "Computer Fundamentals", t: "Ports, buses and the motherboard", ty: "notes", k: "usb hdmi vga serial parallel firewire thunderbolt system bus address data control pci pcie expansion slot" },
  { p: "subjects/computer-fundamentals.html", h: "n-software", s: "Computer Fundamentals", t: "Software and translators", ty: "notes", k: "system application compiler interpreter assembler linker loader high low level machine assembly" },
  { p: "subjects/computer-fundamentals.html", h: "n-malware", s: "Computer Fundamentals", t: "Malware and antivirus", ty: "notes", k: "virus worm trojan ransomware spyware adware rootkit keylogger logic bomb phishing antivirus firewall" },
  { p: "subjects/computer-fundamentals.html", h: "n-ethics", s: "Computer Fundamentals", t: "Ethics and environment — e-waste, green computing", ty: "notes", k: "privacy intellectual property software piracy copyright digital divide ergonomics ewaste recycling" },
  { p: "subjects/computer-fundamentals.html", h: "s1", s: "Computer Fundamentals", t: "Convert 245 to binary, octal, hexadecimal", ty: "solved", k: "decimal base conversion division method" },
  { p: "subjects/computer-fundamentals.html", h: "s2", s: "Computer Fundamentals", t: "Memory speed hierarchy: HDD, L1, RAM, register, SSD", ty: "solved", k: "fastest slowest latency access time order" },
  { p: "subjects/computer-fundamentals.html", h: "s3", s: "Computer Fundamentals", t: "Address bus and data bus — maximum memory", ty: "solved", k: "20-bit 8-bit addressable space 1 MB" },
  { p: "subjects/computer-fundamentals.html", h: "s4", s: "Computer Fundamentals", t: "Compiler vs interpreter vs assembler", ty: "solved", k: "translation source object code machine language" },
  { p: "subjects/computer-fundamentals.html", h: "s5", s: "Computer Fundamentals", t: "Identify malware type — logic bomb, trojan, worm", ty: "solved", k: "date trigger file deletion self replicating" },
  { p: "subjects/computer-fundamentals.html", h: "s6", s: "Computer Fundamentals", t: "Convert 10110011 binary to decimal and hexadecimal", ty: "solved", k: "binary conversion 179 B3" },
  { p: "subjects/computer-fundamentals.html", h: "s7", s: "Computer Fundamentals", t: "Disk capacity calculation — cylinders, heads, sectors", ty: "solved", k: "5000 cylinders storage formula total bytes" },
  { p: "subjects/computer-fundamentals.html", h: "s8", s: "Computer Fundamentals", t: "Compare SRAM and DRAM", ty: "solved", k: "speed cost refresh flip-flop capacitor cache main memory" },
  { p: "subjects/computer-fundamentals.html", h: "s9", s: "Computer Fundamentals", t: "BCD and Excess-3 encoding of 83", ty: "solved", k: "binary coded decimal weighted code" },
  { p: "subjects/computer-fundamentals.html", h: "s10", s: "Computer Fundamentals", t: "Subtraction using 2's complement — 92 minus 45", ty: "solved", k: "signed binary 8-bit overflow" },
  { p: "subjects/computer-fundamentals.html", h: "p1", s: "Computer Fundamentals", t: "Convert 0.6875 to binary", ty: "practice", k: "fractional decimal to binary multiply method" },
  { p: "subjects/computer-fundamentals.html", h: "p2", s: "Computer Fundamentals", t: "Binary to Gray code and back", ty: "practice", k: "xor conversion reflected code" },
  { p: "subjects/computer-fundamentals.html", h: "p3", s: "Computer Fundamentals", t: "Five computer generations — switching technology", ty: "practice", k: "vacuum tube transistor ic vlsi fifth generation" },
  { p: "subjects/computer-fundamentals.html", h: "p4", s: "Computer Fundamentals", t: "USB 3.0 file transfer time calculation", ty: "practice", k: "2 GiB 5 Gbps throughput data rate" },
  { p: "subjects/computer-fundamentals.html", h: "p5", s: "Computer Fundamentals", t: "Computer boot process from power-on to OS", ty: "practice", k: "post bios uefi bootloader mbr kernel" },
  { p: "subjects/computer-fundamentals.html", h: "p6", s: "Computer Fundamentals", t: "ASCII values and arithmetic", ty: "practice", k: "character code 65 uppercase lowercase digit" },
  { p: "subjects/computer-fundamentals.html", h: "p7", s: "Computer Fundamentals", t: "Storage media capacity — CD, DVD, Blu-ray", ty: "practice", k: "700 MB 4.7 GB 25 GB layers comparison" },
  { p: "subjects/computer-fundamentals.html", h: "p8", s: "Computer Fundamentals", t: "Impact vs non-impact printers", ty: "practice", k: "dot matrix daisy wheel laser inkjet thermal" },
  { p: "subjects/computer-fundamentals.html", h: "p9", s: "Computer Fundamentals", t: "Overflow detection in 2's complement addition", ty: "practice", k: "signed 8-bit 120 plus 15 carry sign bit" },
  { p: "subjects/computer-fundamentals.html", h: "p10", s: "Computer Fundamentals", t: "E-waste and green computing practices", ty: "practice", k: "recycling energy star virtualisation power management" },

  /* ------------------------------------------------- c programming */
  { p: "subjects/c-programming.html", h: "n-structure", s: "C Programming", t: "Program structure and compilation", ty: "notes", k: "preprocessor header main return compilation linking loading" },
  { p: "subjects/c-programming.html", h: "n-types", s: "C Programming", t: "Data types, sizeof and qualifiers", ty: "notes", k: "int char float double long short unsigned signed const volatile sizeof" },
  { p: "subjects/c-programming.html", h: "n-operators", s: "C Programming", t: "Operators and precedence", ty: "notes", k: "arithmetic relational logical bitwise assignment ternary comma precedence associativity" },
  { p: "subjects/c-programming.html", h: "n-control", s: "C Programming", t: "Control flow and loop tracing", ty: "notes", k: "if else switch while do for break continue goto nested loop trace" },
  { p: "subjects/c-programming.html", h: "n-functions", s: "C Programming", t: "Functions, recursion and storage classes", ty: "notes", k: "call by value reference return type prototype scope auto static extern register" },
  { p: "subjects/c-programming.html", h: "n-arrays", s: "C Programming", t: "Arrays — 1D and 2D", ty: "notes", k: "declaration initialization traversal multidimensional row column" },
  { p: "subjects/c-programming.html", h: "n-strings", s: "C Programming", t: "Strings and string functions", ty: "notes", k: "null terminator strlen strcpy strcat strcmp strrev char array" },
  { p: "subjects/c-programming.html", h: "n-pointers", s: "C Programming", t: "Pointers and pointer arithmetic", ty: "notes", k: "address dereference null void double pointer array pointer function pointer" },
  { p: "subjects/c-programming.html", h: "n-dynamic", s: "C Programming", t: "Dynamic memory allocation", ty: "notes", k: "malloc calloc realloc free memory leak dangling pointer heap stack" },
  { p: "subjects/c-programming.html", h: "n-structs", s: "C Programming", t: "Structures and unions", ty: "notes", k: "struct union typedef nested structure size padding member access" },
  { p: "subjects/c-programming.html", h: "n-files", s: "C Programming", t: "File handling in C", ty: "notes", k: "fopen fclose fread fwrite fprintf fscanf fgets fputs fseek file modes" },
  { p: "subjects/c-programming.html", h: "n-preprocessor", s: "C Programming", t: "Preprocessor directives", ty: "notes", k: "define include ifdef ifndef undef pragma macro expansion conditional compilation" },
  { p: "subjects/c-programming.html", h: "n-output", s: "C Programming", t: "Output prediction problems", ty: "notes", k: "tricky output printf format specifier side effects sequence point" },
  { p: "subjects/c-programming.html", h: "s1", s: "C Programming", t: "Swap two numbers without a temporary variable", ty: "solved", k: "xor arithmetic method three ways" },
  { p: "subjects/c-programming.html", h: "s2", s: "C Programming", t: "sizeof for all basic types and array", ty: "solved", k: "int char float double pointer 32-bit size" },
  { p: "subjects/c-programming.html", h: "s3", s: "C Programming", t: "Call by value vs call by reference", ty: "solved", k: "swap function pointer parameter passing" },
  { p: "subjects/c-programming.html", h: "s4", s: "C Programming", t: "Pointer and string tracing output", ty: "solved", k: "char pointer array string literal" },
  { p: "subjects/c-programming.html", h: "s5", s: "C Programming", t: "Palindrome check — C program", ty: "solved", k: "string reverse compare two pointer" },
  { p: "subjects/c-programming.html", h: "s6", s: "C Programming", t: "malloc vs calloc vs realloc comparison", ty: "solved", k: "dynamic memory allocation initialization zero" },
  { p: "subjects/c-programming.html", h: "s7", s: "C Programming", t: "Static local variable output", ty: "solved", k: "static int persistent function call count" },
  { p: "subjects/c-programming.html", h: "s8", s: "C Programming", t: "struct vs union sizeof comparison", ty: "solved", k: "size padding alignment largest member" },
  { p: "subjects/c-programming.html", h: "s9", s: "C Programming", t: "Factorial using recursion", ty: "solved", k: "base case recursive call stack trace" },
  { p: "subjects/c-programming.html", h: "s10", s: "C Programming", t: "Pointer arithmetic output prediction", ty: "solved", k: "increment dereference *p++ *++p ++*p" },
  { p: "subjects/c-programming.html", h: "p1", s: "C Programming", t: "Bitwise operators output prediction", ty: "practice", k: "and or xor shift left right complement" },
  { p: "subjects/c-programming.html", h: "p2", s: "C Programming", t: "Reverse a string in place", ty: "practice", k: "two pointer swap char array" },
  { p: "subjects/c-programming.html", h: "p3", s: "C Programming", t: "Macro pitfall — side effects", ty: "practice", k: "define max increment double evaluation" },
  { p: "subjects/c-programming.html", h: "p4", s: "C Programming", t: "Count vowels and consonants in a string", ty: "practice", k: "char comparison loop switch" },
  { p: "subjects/c-programming.html", h: "p5", s: "C Programming", t: "*p++ vs *++p vs ++*p tracing", ty: "practice", k: "pointer dereference increment order" },
  { p: "subjects/c-programming.html", h: "p6", s: "C Programming", t: "Four storage classes explained", ty: "practice", k: "auto static extern register scope lifetime" },
  { p: "subjects/c-programming.html", h: "p7", s: "C Programming", t: "GCD using recursion", ty: "practice", k: "euclid algorithm modulo recursive call" },
  { p: "subjects/c-programming.html", h: "p8", s: "C Programming", t: "String comparison: == vs strcmp", ty: "practice", k: "address comparison content comparison" },
  { p: "subjects/c-programming.html", h: "p9", s: "C Programming", t: "Copy file contents in C", ty: "practice", k: "fgetc fputc feof source destination" },
  { p: "subjects/c-programming.html", h: "p10", s: "C Programming", t: "Assignment vs equality trap output", ty: "practice", k: "= vs == if condition always true" },

  /* ---------------------------------------------------------- database */
  { p: "subjects/database.html", h: "n-fundamentals", s: "Database", t: "Database fundamentals and three-schema architecture", ty: "notes", k: "dbms schema internal conceptual external data independence abstraction" },
  { p: "subjects/database.html", h: "n-er", s: "Database", t: "ER modelling — entities, relationships, cardinality", ty: "notes", k: "entity attribute relationship one to many many to many weak entity participation total partial er diagram" },
  { p: "subjects/database.html", h: "n-relational", s: "Database", t: "Relational model and keys", ty: "notes", k: "primary key candidate key foreign key super key alternate key composite key tuple attribute domain" },
  { p: "subjects/database.html", h: "n-algebra", s: "Database", t: "Relational algebra operations", ty: "notes", k: "select project union intersection difference join cartesian product rename division" },
  { p: "subjects/database.html", h: "n-sql", s: "Database", t: "SQL — DDL, DML, DCL, TCL", ty: "notes", k: "create alter drop insert update delete select where group by having order by join subquery aggregate" },
  { p: "subjects/database.html", h: "n-normalization", s: "Database", t: "Normalization — 1NF through BCNF", ty: "notes", k: "functional dependency partial transitive decomposition anomalies redundancy lossless dependency preserving" },
  { p: "subjects/database.html", h: "n-transactions", s: "Database", t: "Transactions and ACID properties", ty: "notes", k: "atomicity consistency isolation durability commit rollback savepoint schedule serializable" },
  { p: "subjects/database.html", h: "n-concurrency", s: "Database", t: "Concurrency control — locks, 2PL, timestamps", ty: "notes", k: "shared exclusive lock two phase locking deadlock starvation timestamp ordering optimistic" },
  { p: "subjects/database.html", h: "n-recovery", s: "Database", t: "Recovery — log-based and checkpoints", ty: "notes", k: "redo undo write ahead log wal deferred immediate checkpoint shadow paging" },
  { p: "subjects/database.html", h: "n-indexing", s: "Database", t: "Storage and indexing — B-tree, B+ tree, hashing", ty: "notes", k: "primary secondary dense sparse clustered non-clustered b-tree b+ tree static dynamic hashing" },
  { p: "subjects/database.html", h: "n-raid", s: "Database", t: "RAID levels — 0, 1, 5, 6, 10", ty: "notes", k: "striping mirroring parity capacity fault tolerance calculation usable storage" },
  { p: "subjects/database.html", h: "n-triggers", s: "Database", t: "Triggers and views", ty: "notes", k: "before after instead of row level statement level create view updatable materialized" },
  { p: "subjects/database.html", h: "n-nosql", s: "Database", t: "NoSQL, OLAP and CAP theorem", ty: "notes", k: "document key-value column family graph mongodb cassandra data warehouse star schema cap consistency availability partition tolerance" },
  { p: "subjects/database.html", h: "s1", s: "Database", t: "ACID properties with examples", ty: "solved", k: "bank transfer atomicity consistency isolation durability" },
  { p: "subjects/database.html", h: "s2", s: "Database", t: "DDL vs DML differences with examples", ty: "solved", k: "create alter drop insert update delete" },
  { p: "subjects/database.html", h: "s3", s: "Database", t: "Normalize a relation to 3NF step by step", ty: "solved", k: "functional dependency partial transitive decomposition order table" },
  { p: "subjects/database.html", h: "s4", s: "Database", t: "Compare key types in RDBMS", ty: "solved", k: "primary candidate super foreign alternate composite" },
  { p: "subjects/database.html", h: "s5", s: "Database", t: "Write a trigger to prevent low GPA inserts", ty: "solved", k: "before insert raise error trigger example" },
  { p: "subjects/database.html", h: "s6", s: "Database", t: "RAID capacity calculation for 8 disks", ty: "solved", k: "raid 0 1 5 10 usable storage formula" },
  { p: "subjects/database.html", h: "s7", s: "Database", t: "SQL queries — filter, aggregate, count", ty: "solved", k: "where group by having count avg join" },
  { p: "subjects/database.html", h: "s8", s: "Database", t: "B-tree vs B+ tree indexing comparison", ty: "solved", k: "data in leaves linked leaf level range query" },
  { p: "subjects/database.html", h: "s9", s: "Database", t: "Deadlock in DBMS — detection and prevention", ty: "solved", k: "wait-for graph lock ordering timeout" },
  { p: "subjects/database.html", h: "s10", s: "Database", t: "File system vs DBMS comparison", ty: "solved", k: "redundancy inconsistency concurrency security" },
  { p: "subjects/database.html", h: "p1", s: "Database", t: "Find candidate keys from functional dependencies", ty: "practice", k: "closure algorithm attribute set R(A,B,C,D,E)" },
  { p: "subjects/database.html", h: "p2", s: "Database", t: "SQL — find second highest salary", ty: "practice", k: "subquery max not in limit offset dense_rank" },
  { p: "subjects/database.html", h: "p3", s: "Database", t: "HAVING vs WHERE with examples", ty: "practice", k: "aggregate filter group by condition" },
  { p: "subjects/database.html", h: "p4", s: "Database", t: "Four SQL join types compared with output", ty: "practice", k: "inner left right full outer cross join null" },
  { p: "subjects/database.html", h: "p5", s: "Database", t: "CAP theorem and database classification", ty: "practice", k: "mongodb cassandra mysql cp ap ca partition tolerance" },
  { p: "subjects/database.html", h: "p6", s: "Database", t: "View vs materialized view", ty: "practice", k: "virtual stored refresh performance trade-off" },
  { p: "subjects/database.html", h: "p7", s: "Database", t: "RAID calculations for 10 disks of 2 TB", ty: "practice", k: "raid 0 1 5 6 10 fault tolerance usable" },
  { p: "subjects/database.html", h: "p8", s: "Database", t: "Conflict serializability check", ty: "practice", k: "precedence graph cycle serializable schedule" },
  { p: "subjects/database.html", h: "p9", s: "Database", t: "OLTP vs OLAP comparison", ty: "practice", k: "transaction analysis star schema data warehouse real-time" },
  { p: "subjects/database.html", h: "p10", s: "Database", t: "CREATE TABLE with constraints and subquery", ty: "practice", k: "primary key foreign key not null check insert select" },

  /* ---------------------------------------------------------- oop java */
  { p: "subjects/oop-java.html", h: "n-concepts", s: "OOP (Java)", t: "OOP concepts — four pillars", ty: "notes", k: "encapsulation inheritance polymorphism abstraction class object message passing" },
  { p: "subjects/oop-java.html", h: "n-platform", s: "OOP (Java)", t: "Java platform — JDK, JRE, JVM", ty: "notes", k: "bytecode javac jit platform independence compile once run anywhere wora" },
  { p: "subjects/oop-java.html", h: "n-access", s: "OOP (Java)", t: "Access modifiers and keywords", ty: "notes", k: "public private protected default static final abstract synchronized volatile transient" },
  { p: "subjects/oop-java.html", h: "n-constructors", s: "OOP (Java)", t: "Constructors in Java", ty: "notes", k: "default parameterized copy constructor chaining this super overloading" },
  { p: "subjects/oop-java.html", h: "n-inheritance", s: "OOP (Java)", t: "Inheritance — types and the diamond problem", ty: "notes", k: "single multilevel hierarchical multiple interface extends implements super is-a" },
  { p: "subjects/oop-java.html", h: "n-polymorphism", s: "OOP (Java)", t: "Polymorphism — overloading and overriding", ty: "notes", k: "compile time runtime method resolution dynamic binding static binding covariant return" },
  { p: "subjects/oop-java.html", h: "n-abstraction", s: "OOP (Java)", t: "Abstract classes and interfaces", ty: "notes", k: "abstract method concrete class interface default method functional interface java 8" },
  { p: "subjects/oop-java.html", h: "n-exceptions", s: "OOP (Java)", t: "Exception handling — try, catch, finally, throw, throws", ty: "notes", k: "checked unchecked runtime exception error hierarchy custom exception" },
  { p: "subjects/oop-java.html", h: "n-strings", s: "OOP (Java)", t: "Strings — String, StringBuffer, StringBuilder", ty: "notes", k: "immutable pool concatenation equals intern thread safe performance" },
  { p: "subjects/oop-java.html", h: "n-collections", s: "OOP (Java)", t: "Collections framework — List, Set, Map", ty: "notes", k: "arraylist linkedlist hashset treeset hashmap treemap iterator comparable comparator" },
  { p: "subjects/oop-java.html", h: "n-threads", s: "OOP (Java)", t: "Multithreading in Java", ty: "notes", k: "thread runnable start run join sleep wait notify synchronized deadlock" },
  { p: "subjects/oop-java.html", h: "n-packaging", s: "OOP (Java)", t: "JAR, WAR, EAR and .NET comparison", ty: "notes", k: "archive deployment web application enterprise java vs dotnet clr jvm c#" },
  { p: "subjects/oop-java.html", h: "n-output", s: "OOP (Java)", t: "Output prediction — Java tricky questions", ty: "notes", k: "field binding method binding initialization order string pool integer cache" },
  { p: "subjects/oop-java.html", h: "s1", s: "OOP (Java)", t: "Overloading vs overriding comparison", ty: "solved", k: "compile time runtime method signature return type" },
  { p: "subjects/oop-java.html", h: "s2", s: "OOP (Java)", t: "Four pillars of OOP explained", ty: "solved", k: "encapsulation inheritance polymorphism abstraction definition example" },
  { p: "subjects/oop-java.html", h: "s3", s: "OOP (Java)", t: "throw vs throws comparison", ty: "solved", k: "exception declaration propagation method signature" },
  { p: "subjects/oop-java.html", h: "s4", s: "OOP (Java)", t: "JDK vs JRE vs JVM comparison", ty: "solved", k: "development runtime virtual machine components" },
  { p: "subjects/oop-java.html", h: "s5", s: "OOP (Java)", t: "JAR vs WAR vs EAR comparison", ty: "solved", k: "archive packaging deployment servlet ejb" },
  { p: "subjects/oop-java.html", h: "s6", s: "OOP (Java)", t: "Field vs method binding output prediction", ty: "solved", k: "static dynamic binding compile runtime variable hiding" },
  { p: "subjects/oop-java.html", h: "s7", s: "OOP (Java)", t: "Abstract class vs interface comparison", ty: "solved", k: "constructor state method default java 8 when to use" },
  { p: "subjects/oop-java.html", h: "s8", s: "OOP (Java)", t: "Java vs .NET platform comparison", ty: "solved", k: "jvm clr bytecode cil cross platform c# language" },
  { p: "subjects/oop-java.html", h: "s9", s: "OOP (Java)", t: "Exception handling code example", ty: "solved", k: "try catch finally throw throws checked unchecked custom" },
  { p: "subjects/oop-java.html", h: "s10", s: "OOP (Java)", t: "String vs StringBuffer vs StringBuilder", ty: "solved", k: "immutable mutable thread safe performance pool" },
  { p: "subjects/oop-java.html", h: "p1", s: "OOP (Java)", t: "Initialization order output prediction", ty: "practice", k: "static block instance constructor parent child" },
  { p: "subjects/oop-java.html", h: "p2", s: "OOP (Java)", t: "Diamond problem and interface solution", ty: "practice", k: "multiple inheritance ambiguity default method" },
  { p: "subjects/oop-java.html", h: "p3", s: "OOP (Java)", t: "try-catch-finally output prediction", ty: "practice", k: "return in finally exception order" },
  { p: "subjects/oop-java.html", h: "p4", s: "OOP (Java)", t: "HashMap vs Hashtable comparison", ty: "practice", k: "thread safe null keys synchronized performance" },
  { p: "subjects/oop-java.html", h: "p5", s: "OOP (Java)", t: "sleep() vs wait() comparison", ty: "practice", k: "thread lock release monitor object notify" },
  { p: "subjects/oop-java.html", h: "p6", s: "OOP (Java)", t: "Field binding vs method binding output", ty: "practice", k: "variable hiding dynamic dispatch static resolution" },
  { p: "subjects/oop-java.html", h: "p7", s: "OOP (Java)", t: "final keyword — variable, method, class", ty: "practice", k: "constant immutable prevent override inheritance" },
  { p: "subjects/oop-java.html", h: "p8", s: "OOP (Java)", t: "== vs equals() and Integer cache", ty: "practice", k: "reference comparison content comparison -128 to 127" },
  { p: "subjects/oop-java.html", h: "p9", s: "OOP (Java)", t: "ArrayList vs LinkedList comparison", ty: "practice", k: "random access insertion deletion performance" },
  { p: "subjects/oop-java.html", h: "p10", s: "OOP (Java)", t: "String immutability output prediction", ty: "practice", k: "concat pool new object reference" },

  /* ------------------------------------------------ computer architecture */
  { p: "subjects/computer-architecture.html", h: "n-foundations", s: "Computer Architecture", t: "Von Neumann and Harvard architecture", ty: "notes", k: "stored program single bus bottleneck separate memory modified harvard registers pc ir mar mbr" },
  { p: "subjects/computer-architecture.html", h: "n-instructions", s: "Computer Architecture", t: "Instructions and addressing modes", ty: "notes", k: "immediate register direct indirect indexed base relative risc cisc effective address" },
  { p: "subjects/computer-architecture.html", h: "n-arithmetic", s: "Computer Architecture", t: "Computer arithmetic — Booth's and IEEE 754", ty: "notes", k: "multiplication signed binary floating point single double precision bias exponent mantissa normalize" },
  { p: "subjects/computer-architecture.html", h: "n-performance", s: "Computer Architecture", t: "Performance — CPU time and Amdahl's law", ty: "notes", k: "instruction count cpi clock rate mips speedup fraction enhanced bottleneck" },
  { p: "subjects/computer-architecture.html", h: "n-pipeline", s: "Computer Architecture", t: "Pipelining and hazards", ty: "notes", k: "if id ex mem wb stages speedup throughput structural data raw war waw control forwarding branch prediction stall" },
  { p: "subjects/computer-architecture.html", h: "n-cache", s: "Computer Architecture", t: "Cache memory and mapping", ty: "notes", k: "direct fully associative set associative tag index offset amat miss rate hit time write through write back lru" },
  { p: "subjects/computer-architecture.html", h: "n-memory", s: "Computer Architecture", t: "Main and virtual memory — paging and TLB", ty: "notes", k: "page table size page number offset physical address translation tlb hit eat page fault" },
  { p: "subjects/computer-architecture.html", h: "n-secondary", s: "Computer Architecture", t: "Secondary storage and disk timing", ty: "notes", k: "seek time rotational latency transfer time rpm access time calculation" },
  { p: "subjects/computer-architecture.html", h: "n-io", s: "Computer Architecture", t: "I/O organisation — programmed, interrupt, DMA", ty: "notes", k: "polling interrupt driven dma cycle stealing burst mode memory mapped isolated io" },
  { p: "subjects/computer-architecture.html", h: "n-micro", s: "Computer Architecture", t: "Microprocessors — 8085 and 8086", ty: "notes", k: "8-bit 16-bit address bus data bus segmentation physical address biu eu flags registers" },
  { p: "subjects/computer-architecture.html", h: "n-parallel", s: "Computer Architecture", t: "Parallel processing and Flynn's taxonomy", ty: "notes", k: "sisd simd misd mimd multiprocessor multicomputer multicore gpu vector" },
  { p: "subjects/computer-architecture.html", h: "s1", s: "Computer Architecture", t: "Von Neumann vs Harvard architecture comparison", ty: "solved", k: "memory bus bottleneck modified harvard past paper" },
  { p: "subjects/computer-architecture.html", h: "s2", s: "Computer Architecture", t: "IEEE 754 encoding of −13.625", ty: "solved", k: "sign exponent mantissa normalize bias 127 single precision" },
  { p: "subjects/computer-architecture.html", h: "s3", s: "Computer Architecture", t: "CPU time calculation with mixed CPI", ty: "solved", k: "average cpi instruction count clock rate 500 mhz" },
  { p: "subjects/computer-architecture.html", h: "s4", s: "Computer Architecture", t: "Amdahl's law — cache improvement speedup", ty: "solved", k: "fraction enhanced 25% memory 80% reduction overall speedup" },
  { p: "subjects/computer-architecture.html", h: "s5", s: "Computer Architecture", t: "RISC vs CISC comparison", ty: "solved", k: "simple complex fixed variable load store arm x86 past paper" },
  { p: "subjects/computer-architecture.html", h: "s6", s: "Computer Architecture", t: "4-way set associative cache bit-field split", ty: "solved", k: "32 KB 64 byte block tag index offset 32-bit address past paper" },
  { p: "subjects/computer-architecture.html", h: "s7", s: "Computer Architecture", t: "Three I/O methods compared", ty: "solved", k: "programmed interrupt dma cpu utilisation hardware" },
  { p: "subjects/computer-architecture.html", h: "s8", s: "Computer Architecture", t: "Addressing modes with examples and EA", ty: "solved", k: "immediate register direct indirect indexed relative effective address" },
  { p: "subjects/computer-architecture.html", h: "s9", s: "Computer Architecture", t: "Disk access time calculation — 10000 RPM", ty: "solved", k: "seek rotational latency transfer time 50 MB/s" },
  { p: "subjects/computer-architecture.html", h: "s10", s: "Computer Architecture", t: "Flynn's taxonomy with examples", ty: "solved", k: "sisd simd misd mimd gpu multicore" },
  { p: "subjects/computer-architecture.html", h: "p1", s: "Computer Architecture", t: "IEEE 754 encoding of 6.75", ty: "practice", k: "binary normalize sign exponent mantissa positive" },
  { p: "subjects/computer-architecture.html", h: "p2", s: "Computer Architecture", t: "Pipeline speedup for 100 instructions in 5 stages", ty: "practice", k: "ideal speedup throughput k + n - 1" },
  { p: "subjects/computer-architecture.html", h: "p3", s: "Computer Architecture", t: "AMAT calculation and required hit rate", ty: "practice", k: "average memory access time miss rate penalty 30 ns 20 ns" },
  { p: "subjects/computer-architecture.html", h: "p4", s: "Computer Architecture", t: "Three cache mapping techniques compared", ty: "practice", k: "direct fully associative set associative conflict miss hardware cost" },
  { p: "subjects/computer-architecture.html", h: "p5", s: "Computer Architecture", t: "8086 physical address calculation", ty: "practice", k: "segment offset cs ip multiply 16 hexadecimal" },
  { p: "subjects/computer-architecture.html", h: "p6", s: "Computer Architecture", t: "8085 vs 8086 comparison", ty: "practice", k: "data bus address bus segmentation pipeline interrupts" },
  { p: "subjects/computer-architecture.html", h: "p7", s: "Computer Architecture", t: "Page table entries and size calculation", ty: "practice", k: "32-bit virtual 24-bit physical 4 KB page 4 MB" },
  { p: "subjects/computer-architecture.html", h: "p8", s: "Computer Architecture", t: "Three pipeline hazard types with examples", ty: "practice", k: "structural data control forwarding branch prediction stall" },
  { p: "subjects/computer-architecture.html", h: "p9", s: "Computer Architecture", t: "CPU time and MIPS calculation with mixed instruction types", ty: "practice", k: "average cpi arithmetic load branch 1 GHz 476 mips" },
  { p: "subjects/computer-architecture.html", h: "p10", s: "Computer Architecture", t: "Write-through vs write-back cache policies", ty: "practice", k: "consistency dirty bit memory traffic eviction" },

  /* ------------------------------------------------------ operating system */
  { p: "subjects/operating-system.html", h: "n-fundamentals", s: "Operating System", t: "Fundamentals — kernel types, system calls, dual mode", ty: "notes", k: "monolithic microkernel hybrid exokernel shell booting user mode kernel mode os structures" },
  { p: "subjects/operating-system.html", h: "n-os-types", s: "Operating System", t: "Types of OS, and spooling versus buffering", ty: "notes", k: "batch multiprogramming time sharing distributed network real time embedded clustered comparison" },
  { p: "subjects/operating-system.html", h: "n-process", s: "Operating System", t: "Processes and threads", ty: "notes", k: "pcb state diagram context switch fork exec wait exit zombie orphan many to one one to one process vs thread" },
  { p: "subjects/operating-system.html", h: "n-scheduling", s: "Operating System", t: "CPU scheduling algorithms and criteria", ty: "notes", k: "fcfs sjf srtf priority round robin multilevel feedback queue turnaround waiting response convoy effect quantum" },
  { p: "subjects/operating-system.html", h: "n-sync", s: "Operating System", t: "Synchronisation — critical section, semaphores, monitors", ty: "notes", k: "race condition mutual exclusion progress bounded waiting peterson test and set mutex vs semaphore producer consumer readers writers dining philosophers priority inversion" },
  { p: "subjects/operating-system.html", h: "n-deadlock", s: "Operating System", t: "Deadlock — Coffman conditions and the banker's algorithm", ty: "notes", k: "prevention avoidance detection recovery resource allocation graph safe state starvation ostrich" },
  { p: "subjects/operating-system.html", h: "n-memory", s: "Operating System", t: "Memory management — paging, segmentation, fragmentation", ty: "notes", k: "logical physical mmu binding swapping first best worst fit internal external compaction tlb effective access time inverted page table" },
  { p: "subjects/operating-system.html", h: "n-virtual", s: "Operating System", t: "Virtual memory and page replacement", ty: "notes", k: "demand paging page fault handling fifo lru optimal clock second chance lfu belady thrashing working set" },
  { p: "subjects/operating-system.html", h: "n-filesystem", s: "Operating System", t: "File systems — allocation, directories, inodes", ty: "notes", k: "sequential direct indexed access contiguous linked fat bit vector journaling mounting acl ntfs ext4" },
  { p: "subjects/operating-system.html", h: "n-disk", s: "Operating System", t: "Disk scheduling, RAID and I/O", ty: "notes", k: "fcfs sstf scan c-scan look c-look seek rotational latency dma programmed io buffering caching" },
  { p: "subjects/operating-system.html", h: "n-protection", s: "Operating System", t: "Protection and security", ty: "notes", k: "access matrix acl capability list least privilege authentication threats" },
  { p: "subjects/operating-system.html", h: "n-virtualization", s: "Operating System", t: "Virtualisation — hypervisors and containers", ty: "notes", k: "type 1 type 2 bare metal hosted vm versus container isolation" },
  { p: "subjects/operating-system.html", h: "n-linux", s: "Operating System", t: "Linux — permissions, chmod, commands, pipes", ty: "notes", k: "umask filesystem hierarchy grep find ps top kill tar ssh redirection shell" },
  { p: "subjects/operating-system.html", h: "s1", s: "Operating System", t: "Banker's algorithm — need matrix, safe sequence, requests", ty: "solved", k: "avoidance available allocation max safe state unsafe grant deny past paper 2025" },
  { p: "subjects/operating-system.html", h: "s2", s: "Operating System", t: "Can a single process deadlock itself?", ty: "solved", k: "self loop recursive mutex coffman conditions past paper 2024" },
  { p: "subjects/operating-system.html", h: "s3", s: "Operating System", t: "FCFS, SJF, SRTF and round robin with Gantt charts", ty: "solved", k: "average waiting turnaround response time quantum comparison" },
  { p: "subjects/operating-system.html", h: "s4", s: "Operating System", t: "Page replacement — FIFO, LRU, optimal, Belady's anomaly", ty: "solved", k: "reference string frames hit ratio stack algorithm" },
  { p: "subjects/operating-system.html", h: "s5", s: "Operating System", t: "Paging address translation and effective access time", ty: "solved", k: "page number offset frame page table size tlb hit ratio page fault rate slowdown" },
  { p: "subjects/operating-system.html", h: "s6", s: "Operating System", t: "Disk scheduling — six algorithms and total head movement", ty: "solved", k: "fcfs sstf scan c-scan look c-look starvation ssd" },
  { p: "subjects/operating-system.html", h: "s7", s: "Operating System", t: "First fit, best fit and worst fit compared", ty: "solved", k: "partition allocation external fragmentation compaction which succeeds" },
  { p: "subjects/operating-system.html", h: "s8", s: "Operating System", t: "Process versus thread, state diagram, fork counting", ty: "solved", k: "program process thread 2^n processes process tree zombie orphan buffering" },
  { p: "subjects/operating-system.html", h: "s9", s: "Operating System", t: "Producer-consumer with semaphores, and the deadlock if swapped", ty: "solved", k: "race condition critical section mutex empty full mutex vs semaphore" },
  { p: "subjects/operating-system.html", h: "s10", s: "Operating System", t: "Linux permissions, chmod, umask and useful commands", ty: "solved", k: "rwx octal 754 644 symbolic find grep du sort" },
  { p: "subjects/operating-system.html", h: "p1", s: "Operating System", t: "Priority scheduling, preemptive and not, plus aging", ty: "practice", k: "gantt chart starvation indefinite blocking effective priority" },
  { p: "subjects/operating-system.html", h: "p2", s: "Operating System", t: "Breaking each Coffman condition, and cycles in a RAG", ty: "practice", k: "prevention resource ordering proof multiple instances ostrich linux" },
  { p: "subjects/operating-system.html", h: "p3", s: "Operating System", t: "Segmentation translation and paging comparison", ty: "practice", k: "base limit trap segmentation fault segmented paging x86" },
  { p: "subjects/operating-system.html", h: "p4", s: "Operating System", t: "Thrashing, the working set, and frame allocation", ty: "practice", k: "degree of multiprogramming cpu utilisation suspend process equal proportional global local" },
  { p: "subjects/operating-system.html", h: "p5", s: "Operating System", t: "File allocation methods and maximum inode file size", ty: "practice", k: "contiguous linked indexed direct single double triple indirect disk accesses" },
  { p: "subjects/operating-system.html", h: "p6", s: "Operating System", t: "RAID capacity, write penalty and what to run a bank on", ty: "practice", k: "raid 0 1 5 6 10 rebuild time raid is not backup" },
  { p: "subjects/operating-system.html", h: "p7", s: "Operating System", t: "Dining philosophers, readers-writers, priority inversion", ty: "practice", k: "deadlock fix asymmetric ordering monitor writer starvation priority inheritance mars pathfinder" },
  { p: "subjects/operating-system.html", h: "p8", s: "Operating System", t: "Clock (second-chance) page replacement traced", ty: "practice", k: "reference bit hand pointer why not true lru enhanced second chance" },
  { p: "subjects/operating-system.html", h: "p9", s: "Operating System", t: "Multiprogramming vs multiprocessing, spooling, system calls", ty: "practice", k: "concurrency parallelism read syscall trace user kernel mode dual mode" },
  { p: "subjects/operating-system.html", h: "p10", s: "Operating System", t: "Disk access time, IOPS and what changes with an SSD", ty: "practice", k: "seek rotational latency transfer 7200 rpm throughput fragmentation trim wear levelling" },

  // ── Telecommunication ──
  { p: "subjects/telecommunication.html", s: "Telecommunication", t: "Telecommunication", ty: "subject", k: "telecom signals modulation multiplexing wireless mobile" },
  { p: "subjects/telecommunication.html", h: "n-signals", s: "Telecommunication", t: "Signals and transmission basics", ty: "notes", k: "analog digital bandwidth baseband broadband attenuation noise SNR decibel" },
  { p: "subjects/telecommunication.html", h: "n-modulation", s: "Telecommunication", t: "Modulation techniques", ty: "notes", k: "AM FM PM ASK FSK PSK QAM constellation diagram baud rate bit rate" },
  { p: "subjects/telecommunication.html", h: "n-multiplexing", s: "Telecommunication", t: "Multiplexing and spread spectrum", ty: "notes", k: "FDM TDM WDM CDM FHSS DSSS OFDM guard band time slot" },
  { p: "subjects/telecommunication.html", h: "n-media", s: "Telecommunication", t: "Transmission media", ty: "notes", k: "twisted pair coaxial fiber optic UTP STP single multi mode optical wireless" },
  { p: "subjects/telecommunication.html", h: "n-switching", s: "Telecommunication", t: "Switching techniques", ty: "notes", k: "circuit packet message switching virtual store forward datagram" },
  { p: "subjects/telecommunication.html", h: "n-mobile", s: "Telecommunication", t: "Mobile and cellular networks", ty: "notes", k: "1G 2G 3G 4G 5G GSM CDMA LTE cell handover frequency reuse" },
  { p: "subjects/telecommunication.html", h: "n-wireless", s: "Telecommunication", t: "Wireless standards and satellite", ty: "notes", k: "Wi-Fi 802.11 Bluetooth Zigbee NFC RFID LEO MEO GEO satellite VSAT" },
  { p: "subjects/telecommunication.html", h: "n-optical", s: "Telecommunication", t: "Optical networking and submarine cables", ty: "notes", k: "DWDM SONET SDH OTN submarine cable SEA-ME-WE fiber" },
  { p: "subjects/telecommunication.html", h: "n-tic", s: "Telecommunication", t: "Telecom in Bangladesh", ty: "notes", k: "BTRC Teletalk Grameenphone Robi Banglalink spectrum 5G submarine cable" },
  { p: "subjects/telecommunication.html", h: "n-error", s: "Telecommunication", t: "Error detection and correction", ty: "notes", k: "parity CRC checksum Hamming code VRC LRC polynomial" },

  // ── Circuit Analysis ──
  { p: "subjects/circuit-analysis.html", s: "Circuit Analysis", t: "Circuit Analysis", ty: "subject", k: "circuits electronics DC AC diode transistor op-amp" },
  { p: "subjects/circuit-analysis.html", h: "n-dc", s: "Circuit Analysis", t: "DC fundamentals", ty: "notes", k: "Ohm law KVL KCL voltage divider current divider series parallel delta wye" },
  { p: "subjects/circuit-analysis.html", h: "n-theorems", s: "Circuit Analysis", t: "Network theorems", ty: "notes", k: "Thevenin Norton superposition maximum power transfer equivalent circuit" },
  { p: "subjects/circuit-analysis.html", h: "n-energy", s: "Circuit Analysis", t: "Energy storage elements", ty: "notes", k: "capacitor inductor RC transient time constant charging discharging" },
  { p: "subjects/circuit-analysis.html", h: "n-ac", s: "Circuit Analysis", t: "AC analysis", ty: "notes", k: "RMS impedance phasor resonance Q factor power factor real reactive apparent" },
  { p: "subjects/circuit-analysis.html", h: "n-diode", s: "Circuit Analysis", t: "Diodes and rectifiers", ty: "notes", k: "PN junction forward reverse bias half wave full wave bridge Zener regulator ripple" },
  { p: "subjects/circuit-analysis.html", h: "n-clipper", s: "Circuit Analysis", t: "Clippers and clampers", ty: "notes", k: "positive negative clipper clamper waveform shaping diode" },
  { p: "subjects/circuit-analysis.html", h: "n-transistor", s: "Circuit Analysis", t: "Transistors", ty: "notes", k: "BJT NPN PNP alpha beta cutoff active saturation FET MOSFET JFET CE CB CC" },
  { p: "subjects/circuit-analysis.html", h: "n-opamp", s: "Circuit Analysis", t: "Operational amplifiers", ty: "notes", k: "op-amp virtual short inverting non-inverting summing CMRR gain feedback" },

  // ── Discrete Math ──
  { p: "subjects/discrete-math.html", s: "Discrete Math", t: "Discrete Math", ty: "subject", k: "logic sets graphs combinatorics probability boolean automata" },
  { p: "subjects/discrete-math.html", h: "n-logic", s: "Discrete Math", t: "Propositional logic", ty: "notes", k: "connectives truth table tautology contradiction equivalence De Morgan implication" },
  { p: "subjects/discrete-math.html", h: "n-proof", s: "Discrete Math", t: "Proof techniques", ty: "notes", k: "direct contrapositive contradiction induction pigeonhole principle strong" },
  { p: "subjects/discrete-math.html", h: "n-sets", s: "Discrete Math", t: "Set theory, relations, functions", ty: "notes", k: "union intersection complement inclusion exclusion reflexive symmetric transitive injective surjective bijective" },
  { p: "subjects/discrete-math.html", h: "n-counting", s: "Discrete Math", t: "Combinatorics", ty: "notes", k: "permutation combination nPr nCr identical objects MISSISSIPPI multinomial" },
  { p: "subjects/discrete-math.html", h: "n-probability", s: "Discrete Math", t: "Probability", ty: "notes", k: "Bayes theorem conditional expected value random variable independence" },
  { p: "subjects/discrete-math.html", h: "n-graphs", s: "Discrete Math", t: "Graph theory", ty: "notes", k: "degree Euler Hamilton chromatic number planar bipartite Kuratowski" },
  { p: "subjects/discrete-math.html", h: "n-boolean", s: "Discrete Math", t: "Boolean algebra", ty: "notes", k: "AND OR NOT XOR K-map Karnaugh simplification minterm maxterm SOP POS" },
  { p: "subjects/discrete-math.html", h: "n-automata", s: "Discrete Math", t: "Automata and formal languages", ty: "notes", k: "DFA NFA Chomsky hierarchy regular context-free pumping lemma Turing machine" },
  { p: "subjects/discrete-math.html", h: "n-numtheory", s: "Discrete Math", t: "Number theory", ty: "notes", k: "GCD Euclid algorithm modular arithmetic Fermat little theorem Euler totient RSA" },
  { p: "subjects/discrete-math.html", h: "n-recurrence", s: "Discrete Math", t: "Recurrence relations", ty: "notes", k: "characteristic equation Fibonacci closed form master theorem divide conquer" },

  // ── Software Engineering ──
  { p: "subjects/software-engineering.html", s: "Software Engineering", t: "Software Engineering", ty: "subject", k: "SDLC process model testing UML design patterns estimation" },
  { p: "subjects/software-engineering.html", h: "n-process", s: "Software Engineering", t: "Process models", ty: "notes", k: "waterfall V-model iterative spiral agile scrum RAD XP kanban manifesto" },
  { p: "subjects/software-engineering.html", h: "n-requirements", s: "Software Engineering", t: "Requirements engineering", ty: "notes", k: "functional non-functional elicitation MoSCoW SRS stakeholder" },
  { p: "subjects/software-engineering.html", h: "n-design", s: "Software Engineering", t: "Analysis and design", ty: "notes", k: "coupling cohesion architecture MVC SOLID SRP OCP LSP ISP DIP layered" },
  { p: "subjects/software-engineering.html", h: "n-uml", s: "Software Engineering", t: "UML diagrams", ty: "notes", k: "use case class sequence activity state diagram association aggregation composition" },
  { p: "subjects/software-engineering.html", h: "n-patterns", s: "Software Engineering", t: "Design patterns", ty: "notes", k: "singleton factory observer strategy GoF creational structural behavioral" },
  { p: "subjects/software-engineering.html", h: "n-testing", s: "Software Engineering", t: "Software testing", ty: "notes", k: "unit integration system acceptance white box black box boundary value cyclomatic complexity" },
  { p: "subjects/software-engineering.html", h: "n-estimation", s: "Software Engineering", t: "Estimation techniques", ty: "notes", k: "COCOMO function point FPA LOC organic semi-detached embedded effort schedule" },
  { p: "subjects/software-engineering.html", h: "n-project", s: "Software Engineering", t: "Project management", ty: "notes", k: "CPM PERT critical path Gantt chart slack float network diagram" },
  { p: "subjects/software-engineering.html", h: "n-maintenance", s: "Software Engineering", t: "Maintenance and quality", ty: "notes", k: "corrective adaptive perfective preventive CMMI level capability maturity" },

  // ── Security ──
  { p: "subjects/security.html", s: "Security", t: "Security", ty: "subject", k: "cybersecurity cryptography encryption firewall authentication" },
  { p: "subjects/security.html", h: "n-cia", s: "Security", t: "CIA triad and security principles", ty: "notes", k: "confidentiality integrity availability authentication non-repudiation" },
  { p: "subjects/security.html", h: "n-malware", s: "Security", t: "Malware types", ty: "notes", k: "virus worm trojan ransomware spyware rootkit adware keylogger" },
  { p: "subjects/security.html", h: "n-netattack", s: "Security", t: "Network attacks", ty: "notes", k: "DoS DDoS MITM ARP spoofing DNS spoofing IP spoofing replay session hijacking" },
  { p: "subjects/security.html", h: "n-appattack", s: "Security", t: "Application attacks", ty: "notes", k: "SQL injection XSS CSRF buffer overflow OWASP top 10" },
  { p: "subjects/security.html", h: "n-social", s: "Security", t: "Social engineering", ty: "notes", k: "phishing spear phishing vishing smishing pretexting baiting tailgating" },
  { p: "subjects/security.html", h: "n-symmetric", s: "Security", t: "Symmetric cryptography", ty: "notes", k: "DES 3DES AES Blowfish RC4 block cipher mode ECB CBC CTR key distribution" },
  { p: "subjects/security.html", h: "n-asymmetric", s: "Security", t: "Asymmetric cryptography", ty: "notes", k: "RSA Diffie-Hellman ECC DSA public private key hybrid encryption" },
  { p: "subjects/security.html", h: "n-hash", s: "Security", t: "Hashing and digital signatures", ty: "notes", k: "MD5 SHA-1 SHA-256 SHA-3 HMAC digital signature certificate PKI" },
  { p: "subjects/security.html", h: "n-auth", s: "Security", t: "Authentication and access control", ty: "notes", k: "MFA biometric DAC MAC RBAC ABAC password hashing bcrypt" },
  { p: "subjects/security.html", h: "n-defence", s: "Security", t: "Network defence and governance", ty: "notes", k: "firewall IDS IPS WAF VPN DMZ SIEM SOC ISO 27001 NIST PCI-DSS" },

  // ── Other Topics ──
  { p: "subjects/other-topics.html", s: "Other Topics", t: "Other Topics", ty: "subject", k: "web HTTP REST data centre digital logic Bangladesh ICT policy" },
  { p: "subjects/other-topics.html", h: "n-web", s: "Other Topics", t: "Web technology", ty: "notes", k: "HTML CSS JavaScript semantic elements flexbox grid CSR SSR SPA responsive" },
  { p: "subjects/other-topics.html", h: "n-http", s: "Other Topics", t: "HTTP, REST and APIs", ty: "notes", k: "GET POST PUT DELETE status code 200 404 500 REST SOAP API endpoint" },
  { p: "subjects/other-topics.html", h: "n-dc", s: "Other Topics", t: "Data centre infrastructure", ty: "notes", k: "UPS HVAC fire suppression PUE tier classification RPO RTO hot warm cold site" },
  { p: "subjects/other-topics.html", h: "n-logic", s: "Other Topics", t: "Digital logic", ty: "notes", k: "AND OR NOT NAND NOR XOR XNOR universal gate half adder full adder" },
  { p: "subjects/other-topics.html", h: "n-bdpolicy", s: "Other Topics", t: "Bangladesh ICT policy", ty: "notes", k: "ICT Act 2006 Digital Security Act a2i Hi-Tech Park BNDA Smart Bangladesh BACH BEFTN RTGS NPS MFS" },

  // ── Banking ICT ──
  { p: "subjects/banking-ict.html", s: "Banking ICT", t: "Banking ICT", ty: "subject", k: "core banking payment BACH BEFTN RTGS MFS cards EMV digital banking BCP DR" },
  { p: "subjects/banking-ict.html", h: "n-cbs", s: "Banking ICT", t: "Core banking systems", ty: "notes", k: "CBS centralised database Flexcube Temenos Finacle Ababil any-branch banking" },
  { p: "subjects/banking-ict.html", h: "n-payment", s: "Banking ICT", t: "Payment systems (BACH, BEFTN, RTGS)", ty: "notes", k: "clearing house net settlement gross settlement cheque truncation SWIFT NPS" },
  { p: "subjects/banking-ict.html", h: "n-cards", s: "Banking ICT", t: "Cards and switching", ty: "notes", k: "debit credit prepaid EMV chip magnetic stripe ATM switch POS acquirer issuer interchange" },
  { p: "subjects/banking-ict.html", h: "n-mfs", s: "Banking ICT", t: "Mobile financial services", ty: "notes", k: "bKash Nagad Rocket USSD agent network cash-in cash-out P2P KYC NID" },
  { p: "subjects/banking-ict.html", h: "n-digital", s: "Banking ICT", t: "Digital and internet banking", ty: "notes", k: "internet banking mobile banking MFA OTP SSL TLS Bangla QR open banking" },
  { p: "subjects/banking-ict.html", h: "n-security", s: "Banking ICT", t: "Banking security and compliance", ty: "notes", k: "PCI-DSS ISO 27001 SWIFT CSP VAPT CISO SOC BB ICT guidelines AML KYC" },
  { p: "subjects/banking-ict.html", h: "n-bcp", s: "Banking ICT", t: "Business continuity", ty: "notes", k: "BCP DR RPO RTO hot site warm site cold site disaster recovery drill" },
  { p: "subjects/banking-ict.html", h: "n-fintech", s: "Banking ICT", t: "Emerging finance and fintech", ty: "notes", k: "fintech regtech insurtech CBDC digital taka regulatory sandbox QR payment" },

  // ── Emerging Tech ──
  { p: "subjects/emerging-tech.html", s: "Emerging Tech", t: "Emerging Tech", ty: "subject", k: "cloud big data AI ML IoT blockchain 5G quantum RPA" },
  { p: "subjects/emerging-tech.html", h: "n-cloud", s: "Emerging Tech", t: "Cloud computing", ty: "notes", k: "IaaS PaaS SaaS public private hybrid community NIST elasticity on-demand" },
  { p: "subjects/emerging-tech.html", h: "n-bigdata", s: "Emerging Tech", t: "Big data and analytics", ty: "notes", k: "5 Vs volume velocity variety veracity value Hadoop HDFS MapReduce Spark data lake warehouse" },
  { p: "subjects/emerging-tech.html", h: "n-aiml", s: "Emerging Tech", t: "Artificial intelligence and machine learning", ty: "notes", k: "supervised unsupervised reinforcement neural network CNN RNN deep learning NLP chatbot" },
  { p: "subjects/emerging-tech.html", h: "n-iot", s: "Emerging Tech", t: "Internet of Things", ty: "notes", k: "IoT sensor MQTT CoAP Zigbee LoRa edge computing smart ATM wearable" },
  { p: "subjects/emerging-tech.html", h: "n-blockchain", s: "Emerging Tech", t: "Blockchain and distributed ledger", ty: "notes", k: "blockchain PoW PoS PBFT smart contract Ethereum Hyperledger consortium immutable" },
  { p: "subjects/emerging-tech.html", h: "n-frontier", s: "Emerging Tech", t: "Frontier technologies", ty: "notes", k: "5G quantum computing post-quantum RPA digital twin zero trust AR VR" },

  // ── Focus Writing ──
  { p: "subjects/focus-writing.html", s: "Focus Writing", t: "Focus Writing", ty: "subject", k: "essay report structure fact bank model answer writing exam" },
  { p: "subjects/focus-writing.html", h: "n-structure", s: "Focus Writing", t: "Reusable essay structure", ty: "notes", k: "5-paragraph template hook definition body conclusion BD context" },
  { p: "subjects/focus-writing.html", h: "n-facts", s: "Focus Writing", t: "Fact bank", ty: "notes", k: "statistics MFS BACH BEFTN RTGS SWIFT heist Smart Bangladesh ICT policy" },
  { p: "subjects/focus-writing.html", h: "n-language", s: "Focus Writing", t: "Language toolkit", ty: "notes", k: "opening hook transition phrase closing sentence professional English" },
  { p: "subjects/focus-writing.html", h: "n-pitfalls", s: "Focus Writing", t: "Common pitfalls and scoring", ty: "notes", k: "scoring criteria technical accuracy BD relevance balanced view time budget" },
  { p: "subjects/focus-writing.html", h: "n-prompts", s: "Focus Writing", t: "Prompt analysis", ty: "notes", k: "discuss explain compare role of challenges impact prompt keyword" },

  // ── Past Papers ──
  { p: "past-papers.html", s: "Past Papers", t: "Past Papers — Solved", ty: "subject", k: "past paper exam previous year BB AD ICT Combined Officer 2025 2024" },
  { p: "past-papers.html", h: "paper-2025", s: "Past Papers", t: "BB AD (ICT) — 07/02/2025", ty: "notes", k: "Bangladesh Bank AD ICT 2025 written exam paper" },
  { p: "past-papers.html", h: "pp25-q1", s: "Past Papers", t: "Min-heap construction from array", ty: "solved", k: "min heap array heapify tree construction build" },
  { p: "past-papers.html", h: "pp25-q2", s: "Past Papers", t: "Dhaka–Rangpur packet latency and RTT", ty: "solved", k: "transmission delay propagation latency RTT bandwidth-delay product stop-and-wait efficiency" },
  { p: "past-papers.html", h: "pp25-q3", s: "Past Papers", t: "SMTP POP3 IMAP email flow", ty: "solved", k: "email SMTP POP3 IMAP mail server sender receiver protocol comparison" },
  { p: "past-papers.html", h: "pp25-q4", s: "Past Papers", t: "Banker's algorithm safe sequence", ty: "solved", k: "banker algorithm deadlock avoidance safe state need matrix available resource" },
  { p: "past-papers.html", h: "pp25-q5", s: "Past Papers", t: "Normalization to 3NF", ty: "solved", k: "normalization 1NF 2NF 3NF functional dependency candidate key decomposition" },
  { p: "past-papers.html", h: "pp25-q6", s: "Past Papers", t: "Tautology proof p→(q→p)", ty: "solved", k: "tautology truth table implication logical proposition" },
  { p: "past-papers.html", h: "paper-2024", s: "Past Papers", t: "Combined Officer (IT) — 04/10/2024", ty: "notes", k: "Combined Bank Officer IT 2024 written exam paper" },
  { p: "past-papers.html", h: "pp24-q1", s: "Past Papers", t: "Flow control vs congestion control", ty: "solved", k: "TCP flow control congestion control sliding window AIMD slow start" },
  { p: "past-papers.html", h: "pp24-q2", s: "Past Papers", t: "Single-process deadlock analysis", ty: "solved", k: "deadlock single process four conditions mutual exclusion hold-and-wait" },
  { p: "past-papers.html", h: "pp24-q3", s: "Past Papers", t: "12-bit DAC resolution and output", ty: "solved", k: "DAC digital-to-analog converter resolution reference voltage bit output" },
  { p: "past-papers.html", h: "pp24-q4", s: "Past Papers", t: "Cache bit-field split (4-way set associative)", ty: "solved", k: "cache set associative tag index offset block size address bits" },
  { p: "past-papers.html", h: "pp24-q5", s: "Past Papers", t: "Set theory inclusion-exclusion", ty: "solved", k: "set union intersection difference inclusion exclusion cardinality" },
  { p: "past-papers.html", h: "pp24-q6", s: "Past Papers", t: "Probability sum of two dice equals 7", ty: "solved", k: "probability dice sum sample space favorable outcome" },
  { p: "past-papers.html", h: "pp24-q7", s: "Past Papers", t: "Use-case diagram for online purchase", ty: "solved", k: "use case diagram actor include extend UML online purchase system" }
];
